pipeline:
  build:
    image: ${IMAGE}:${TAG}
    commands:
      - cd dependencies
      - set -x && bash install_dependencies_minimal.sh ${IMAGE} && set +x
      - cd ..
      - export LANG=en_US.UTF-8
      - export LC_ALL=en_US.UTF-8
      - export LANGUAGE=en_US:en
      - locale
      - python --version
      - python -c "import numpy; print numpy.__version__"
      - python -c "import scipy; print scipy.__version__"
      - gcc --version
      - gcc -march=native -Q --help=target
      - mkdir -p ~/.config/matplotlib
      - 'echo "backend : Agg" > ~/.config/matplotlib/matplotlibrc'
      - make -C project2 jacobi_lib
      - make -C project2 benchmarks
      - make -C project2 test
      - make -C project3 solar_system_lib
      - make -C project3 reference_test
      - make -C project4 libising
      - make -C project4 reference_test
      - make -C project5 diffusion_lib
      - make -C project5 clean-c
      - make -C project5 test
      - make -C project5 clean-c
      #- make -C project5 diffusion_lib_mpi

matrix:
  include:
    - IMAGE: fedora
      TAG: latest
    - IMAGE: ubuntu
      TAG: latest     # latest LTS release
    - IMAGE: ubuntu
      TAG: rolling    # latest release
