pipeline:
  build:
    image: fedora
    commands:
      - set -x && sudo bash dependencies/install_dependencies_fed.sh
      - python --version
      - python -c "import numpy"
      - make -C project2 jacobi_lib
      - make -C project3 solar_system_lib
      - make -C project4 libising
      - make -C project5 diffusion_lib
      - make -C project5 clean-c
      - make -C project5 test
      - make -C project5 clean-c
      - make -C project5 diffusion_lib_mpi
