pipeline:
  build:
    image: ${IMAGE}
    commands:
      - cd dependencies
      - set -x && bash install_dependencies_minimal.sh ${IMAGE} && set +x
      - cd ..
      - python --version
      - python -c "import numpy; print numpy.__version__"
      - gcc --version
      - gcc -march=native -Q --help=target
      - make -C project2 jacobi_lib
      - make -C project3 solar_system_lib
      - make -C project4 libising
      - make -C project5 diffusion_lib
      - make -C project5 clean-c
      - make -C project5 test
      - make -C project5 clean-c
      #- make -C project5 diffusion_lib_mpi

matrix:
  IMAGE:
    - fedora
    - ubuntu
