language: python
python:
    - "2.7"

dist: trusty
sudo: false 

before_install:
    - pip install tabulate

addons:
  apt:
    packages:
    - libgsl0-dev
    - libatlas-base-dev
    - openmpi-bin
    - libopenmpi-dev
    - valgrind
    - python-numpy
    - python-scipy
    - python-matplotlib

env:
    - OMP_NUM_THREADS=4
script:
    - python --version
    - python -c "import numpy"
    - make -C project2 jacobi_lib
    - make -C project3 solar_system_lib
    - make -C project4 libising
    - make -C project5 diffusion_lib
    - make -C project5 clean-c
    - make -C project5 test
    - make -C project5 clean-c
    - make -C project5 diffusion_lib_mpi

notifications:
    email: false
