language: python
python:
    - "2.7"

sudo: false

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo $CONDA_DIR; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget --quiet https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh && bash Miniconda2-latest-MacOSX-x86_64.sh -b -p $CONDA_DIR; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$CONDA_DIR/bin:$PATH; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then conda config --system --append channels conda-forge; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then conda update --all -y; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then conda create -n dev python=2.7 -y; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source activate dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash dependencies/install_dependencies_conda.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source deactivate; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source activate dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install weave; fi
    - pip install tabulate

addons:
  apt:
    packages:
    - libgsl0-dev
    - libatlas-base-dev
    - openmpi-bin
    - libopenmpi-dev
    - valgrind
    - python-numpy
    - python-scipy
    - python-matplotlib

env:
    - OMP_NUM_THREADS=4 CONDA_DIR=$HOME/conda
script:
    - which python
    - python --version
    - python -c "import numpy; print numpy.__version__"
    - python -c "import scipy; print scipy.__version__"
    - make -C project2 jacobi_lib
    - make -C project3 solar_system_lib
    - make -C project4 libising
    - make -C project5 diffusion_lib
    - make -C project5 clean-c
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -C project5 test; else make -C project5 pytest; fi
    - make -C project5 clean-c
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -C project5 diffusion_lib_mpi; fi

notifications:
    email: false

virtualenv:
    system_site_packages: true

matrix:
    include:
        - language: generic
          os: osx
        - language: python
          os: linux
          dist: trusty