language: c
compiler: gcc

dist: trusty
sudo: required

before_install:
    - sudo -H pip install pytest
    - pip install --user tabulate

addons:
  apt:
    packages:
    - libgsl0-dev
    - libatlas-base-dev
    - openmpi-bin
    - libopenmpi-dev
    - valgrind

env:
    - OMP_NUM_THREADS=4
script:
    - make -C project2 jacobi_lib
    - make -C project3 solar_system_lib
    - make -C project4 libising
    - make -C project5 diffusion_lib
    - make -C project5 clean-c
    - make -C project5/src/c memtest
    - make -C project5/ clean-c
    - make -C project5 diffusion_lib_mpi

notifications:
    email: false
