language: c

compiler: gcc

before_install:
    - pip install --user tabulate

addons:
  apt:
    packages:
    - libgls-dev
    - libatlas-base-dev
    - openmpi-bin
    - libopenmpi-dev

env:
    - OMP_NUM_THREADS=4
script:
    - cd project2 && make jacobi_lib && cd -
    - cd project3 && make solar_system_lib && cd -
    - cd project4 && make libising && cd -
    - cd project5 && make diffusion_lib && make clean-c && cd -
    - cd project5 && make diffusion_lib_mpi && cd -

notifications:
    email: false
